name: Backend budtree_app

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Java 17 버전 사용
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image Build and Push to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/budtree_app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/budtree_app:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/compose
            docker compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/budtree_app:latest
            docker compose up --build -d
            docker image prune -f